In [1]:
%matplotlib inline

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
!ls -l /home/shared/sp18-is590dv/data/names/

total 23916
-rw-r--r-- 1 mjturk users    394 Mar 31  2017 collect.py
-rw-r--r-- 1 mjturk users 220267 Apr  4  2016 NationalReadMe.pdf
-rw-r--r-- 1 mjturk users  24933 Apr  4  2016 yob1880.txt
-rw-r--r-- 1 mjturk users  24065 Apr  4  2016 yob1881.txt
-rw-r--r-- 1 mjturk users  26559 Apr  4  2016 yob1882.txt
-rw-r--r-- 1 mjturk users  26002 Apr  4  2016 yob1883.txt
-rw-r--r-- 1 mjturk users  28670 Apr  4  2016 yob1884.txt
-rw-r--r-- 1 mjturk users  28625 Apr  4  2016 yob1885.txt
-rw-r--r-- 1 mjturk users  29822 Apr  4  2016 yob1886.txt
-rw-r--r-- 1 mjturk users  29531 Apr  4  2016 yob1887.txt
-rw-r--r-- 1 mjturk users  33064 Apr  4  2016 yob1888.txt
-rw-r--r-- 1 mjturk users  32297 Apr  4  2016 yob1889.txt
-rw-r--r-- 1 mjturk users  33621 Apr  4  2016 yob1890.txt
-rw-r--r-- 1 mjturk users  33186 Apr  4  2016 yob1891.txt
-rw-r--r-- 1 mjturk users  36542 Apr  4  2016 yob1892.txt
-rw-r--r-- 1 mjturk users  35433 Apr  4  2016 yob1893.txt
-rw-r--r-- 1 mjturk users  36817 Apr  4  2016 yob1894.txt
-rw-r--r-- 1 mjturk users  38232 Apr  4  2016 yob1895.txt
-rw-r--r-- 1 mjturk users  38747 Apr  4  2016 yob1896.txt
-rw-r--r-- 1 mjturk users  37936 Apr  4  2016 yob1897.txt
-rw-r--r-- 1 mjturk users  40924 Apr  4  2016 yob1898.txt
-rw-r--r-- 1 mjturk users  38141 Apr  4  2016 yob1899.txt
-rw-r--r-- 1 mjturk users  46873 Apr  4  2016 yob1900.txt
-rw-r--r-- 1 mjturk users  39584 Apr  4  2016 yob1901.txt
-rw-r--r-- 1 mjturk users  42284 Apr  4  2016 yob1902.txt
-rw-r--r-- 1 mjturk users  42679 Apr  4  2016 yob1903.txt
-rw-r--r-- 1 mjturk users  44819 Apr  4  2016 yob1904.txt
-rw-r--r-- 1 mjturk users  46003 Apr  4  2016 yob1905.txt
-rw-r--r-- 1 mjturk users  45845 Apr  4  2016 yob1906.txt
-rw-r--r-- 1 mjturk users  49829 Apr  4  2016 yob1907.txt
-rw-r--r-- 1 mjturk users  50841 Apr  4  2016 yob1908.txt
-rw-r--r-- 1 mjturk users  53501 Apr  4  2016 yob1909.txt
-rw-r--r-- 1 mjturk users  58710 Apr  4  2016 yob1910.txt
-rw-r--r-- 1 mjturk users  61761 Apr  4  2016 yob1911.txt
-rw-r--r-- 1 mjturk users  80729 Apr  4  2016 yob1912.txt
-rw-r--r-- 1 mjturk users  88692 Apr  4  2016 yob1913.txt
-rw-r--r-- 1 mjturk users 101531 Apr  4  2016 yob1914.txt
-rw-r--r-- 1 mjturk users 119443 Apr  4  2016 yob1915.txt
-rw-r--r-- 1 mjturk users 123876 Apr  4  2016 yob1916.txt
-rw-r--r-- 1 mjturk users 126796 Apr  4  2016 yob1917.txt
-rw-r--r-- 1 mjturk users 133091 Apr  4  2016 yob1918.txt
-rw-r--r-- 1 mjturk users 132711 Apr  4  2016 yob1919.txt
-rw-r--r-- 1 mjturk users 137753 Apr  4  2016 yob1920.txt
-rw-r--r-- 1 mjturk users 139180 Apr  4  2016 yob1921.txt
-rw-r--r-- 1 mjturk users 138171 Apr  4  2016 yob1922.txt
-rw-r--r-- 1 mjturk users 136644 Apr  4  2016 yob1923.txt
-rw-r--r-- 1 mjturk users 139608 Apr  4  2016 yob1924.txt
-rw-r--r-- 1 mjturk users 136815 Apr  4  2016 yob1925.txt
-rw-r--r-- 1 mjturk users 134323 Apr  4  2016 yob1926.txt
-rw-r--r-- 1 mjturk users 133869 Apr  4  2016 yob1927.txt
-rw-r--r-- 1 mjturk users 130708 Apr  4  2016 yob1928.txt
-rw-r--r-- 1 mjturk users 126394 Apr  4  2016 yob1929.txt
-rw-r--r-- 1 mjturk users 125915 Apr  4  2016 yob1930.txt
-rw-r--r-- 1 mjturk users 119556 Apr  4  2016 yob1931.txt
-rw-r--r-- 1 mjturk users 120808 Apr  4  2016 yob1932.txt
-rw-r--r-- 1 mjturk users 115876 Apr  4  2016 yob1933.txt
-rw-r--r-- 1 mjturk users 118071 Apr  4  2016 yob1934.txt
-rw-r--r-- 1 mjturk users 116277 Apr  4  2016 yob1935.txt
-rw-r--r-- 1 mjturk users 114325 Apr  4  2016 yob1936.txt
-rw-r--r-- 1 mjturk users 115331 Apr  4  2016 yob1937.txt
-rw-r--r-- 1 mjturk users 116337 Apr  4  2016 yob1938.txt
-rw-r--r-- 1 mjturk users 114807 Apr  4  2016 yob1939.txt
-rw-r--r-- 1 mjturk users 115634 Apr  4  2016 yob1940.txt
-rw-r--r-- 1 mjturk users 117244 Apr  4  2016 yob1941.txt
-rw-r--r-- 1 mjturk users 121635 Apr  4  2016 yob1942.txt
-rw-r--r-- 1 mjturk users 121484 Apr  4  2016 yob1943.txt
-rw-r--r-- 1 mjturk users 118125 Apr  4  2016 yob1944.txt
-rw-r--r-- 1 mjturk users 116527 Apr  4  2016 yob1945.txt
-rw-r--r-- 1 mjturk users 125430 Apr  4  2016 yob1946.txt
-rw-r--r-- 1 mjturk users 134051 Apr  4  2016 yob1947.txt
-rw-r--r-- 1 mjturk users 132391 Apr  4  2016 yob1948.txt
-rw-r--r-- 1 mjturk users 132800 Apr  4  2016 yob1949.txt
-rw-r--r-- 1 mjturk users 133301 Apr  4  2016 yob1950.txt
-rw-r--r-- 1 mjturk users 135460 Apr  4  2016 yob1951.txt
-rw-r--r-- 1 mjturk users 137733 Apr  4  2016 yob1952.txt
-rw-r--r-- 1 mjturk users 140053 Apr  4  2016 yob1953.txt
-rw-r--r-- 1 mjturk users 141585 Apr  4  2016 yob1954.txt
-rw-r--r-- 1 mjturk users 143595 Apr  4  2016 yob1955.txt
-rw-r--r-- 1 mjturk users 146572 Apr  4  2016 yob1956.txt
-rw-r--r-- 1 mjturk users 149141 Apr  4  2016 yob1957.txt
-rw-r--r-- 1 mjturk users 148688 Apr  4  2016 yob1958.txt
-rw-r--r-- 1 mjturk users 151998 Apr  4  2016 yob1959.txt
-rw-r--r-- 1 mjturk users 154075 Apr  4  2016 yob1960.txt
-rw-r--r-- 1 mjturk users 157555 Apr  4  2016 yob1961.txt
-rw-r--r-- 1 mjturk users 157952 Apr  4  2016 yob1962.txt
-rw-r--r-- 1 mjturk users 158842 Apr  4  2016 yob1963.txt
-rw-r--r-- 1 mjturk users 160538 Apr  4  2016 yob1964.txt
-rw-r--r-- 1 mjturk users 155023 Apr  4  2016 yob1965.txt
-rw-r--r-- 1 mjturk users 157375 Apr  4  2016 yob1966.txt
-rw-r--r-- 1 mjturk users 160642 Apr  4  2016 yob1967.txt
-rw-r--r-- 1 mjturk users 167378 Apr  4  2016 yob1968.txt
-rw-r--r-- 1 mjturk users 177953 Apr  4  2016 yob1969.txt
-rw-r--r-- 1 mjturk users 191549 Apr  4  2016 yob1970.txt
-rw-r--r-- 1 mjturk users 198114 Apr  4  2016 yob1971.txt
-rw-r--r-- 1 mjturk users 199478 Apr  4  2016 yob1972.txt
-rw-r--r-- 1 mjturk users 202968 Apr  4  2016 yob1973.txt
-rw-r--r-- 1 mjturk users 210433 Apr  4  2016 yob1974.txt
-rw-r--r-- 1 mjturk users 219074 Apr  4  2016 yob1975.txt
-rw-r--r-- 1 mjturk users 224972 Apr  4  2016 yob1976.txt
-rw-r--r-- 1 mjturk users 234970 Apr  4  2016 yob1977.txt
-rw-r--r-- 1 mjturk users 235905 Apr  4  2016 yob1978.txt
-rw-r--r-- 1 mjturk users 246394 Apr  4  2016 yob1979.txt
-rw-r--r-- 1 mjturk users 251301 Apr  4  2016 yob1980.txt
-rw-r--r-- 1 mjturk users 251832 Apr  4  2016 yob1981.txt
-rw-r--r-- 1 mjturk users 254727 Apr  4  2016 yob1982.txt
-rw-r--r-- 1 mjturk users 250849 Apr  4  2016 yob1983.txt
-rw-r--r-- 1 mjturk users 252673 Apr  4  2016 yob1984.txt
-rw-r--r-- 1 mjturk users 260221 Apr  4  2016 yob1985.txt
-rw-r--r-- 1 mjturk users 267937 Apr  4  2016 yob1986.txt
-rw-r--r-- 1 mjturk users 278317 Apr  4  2016 yob1987.txt
-rw-r--r-- 1 mjturk users 290985 Apr  4  2016 yob1988.txt
-rw-r--r-- 1 mjturk users 309476 Apr  4  2016 yob1989.txt
-rw-r--r-- 1 mjturk users 322038 Apr  4  2016 yob1990.txt
-rw-r--r-- 1 mjturk users 327138 Apr  4  2016 yob1991.txt
-rw-r--r-- 1 mjturk users 331483 Apr  4  2016 yob1992.txt
-rw-r--r-- 1 mjturk users 337831 Apr  4  2016 yob1993.txt
-rw-r--r-- 1 mjturk users 338232 Apr  4  2016 yob1994.txt
-rw-r--r-- 1 mjturk users 339135 Apr  4  2016 yob1995.txt
-rw-r--r-- 1 mjturk users 343005 Apr  4  2016 yob1996.txt
-rw-r--r-- 1 mjturk users 350047 Apr  4  2016 yob1997.txt
-rw-r--r-- 1 mjturk users 361529 Apr  4  2016 yob1998.txt
-rw-r--r-- 1 mjturk users 369316 Apr  4  2016 yob1999.txt
-rw-r--r-- 1 mjturk users 384997 Apr  4  2016 yob2000.txt
-rw-r--r-- 1 mjturk users 391046 Apr  4  2016 yob2001.txt
-rw-r--r-- 1 mjturk users 394750 Apr  4  2016 yob2002.txt
-rw-r--r-- 1 mjturk users 402539 Apr  4  2016 yob2003.txt
-rw-r--r-- 1 mjturk users 413392 Apr  4  2016 yob2004.txt
-rw-r--r-- 1 mjturk users 420090 Apr  4  2016 yob2005.txt
-rw-r--r-- 1 mjturk users 440170 Apr  4  2016 yob2006.txt
-rw-r--r-- 1 mjturk users 451142 Apr  4  2016 yob2007.txt
-rw-r--r-- 1 mjturk users 452498 Apr  4  2016 yob2008.txt
-rw-r--r-- 1 mjturk users 447775 Apr  4  2016 yob2009.txt
-rw-r--r-- 1 mjturk users 439307 Apr  4  2016 yob2010.txt
-rw-r--r-- 1 mjturk users 436774 Apr  4  2016 yob2011.txt
-rw-r--r-- 1 mjturk users 434402 Apr  4  2016 yob2012.txt
-rw-r--r-- 1 mjturk users 428086 Apr  4  2016 yob2013.txt
-rw-r--r-- 1 mjturk users 427208 Apr  4  2016 yob2014.txt
-rw-r--r-- 1 mjturk users 423906 Apr  4  2016 yob2015.txt

In [4]:
!head /home/shared/sp18-is590dv/data/names/yob1940.txt

In [6]:
df1940 = pd.read_csv("/home/shared/sp18-is590dv/data/names/yob1940.txt", header=None, names = ["name", "sex", "count"])

In [8]:
import glob

In [10]:
fns = sorted(glob.glob("/home/shared/sp18-is590dv/data/names/yob*.txt"))

In [56]:
data = []
for fn in fns:
    year = int(fn[-8:-4])
    df = pd.read_csv(fn, header=None, names = ["name", "sex", "count"])
    df["year"] = year
    data.append(df)

In [57]:
all_names = pd.concat(data)

In [58]:
most_common = []
for year, df in all_names.groupby("year"):
    imax = df["count"].idxmax()
    most_common.append((year, df["name"].loc[imax], df["count"].max()))
most_common = pd.DataFrame(most_common, columns = ["year", "name", "count"])
most_common.set_index("year", inplace=True)

In [59]:
most_common.head()

      name  count
year
1880  John   9655
1881  John   8769
1882  John   9557
1883  John   8894
1884  John   9388

In [60]:
most_common.to_csv("idyll-project1/data/most_common.csv")

In [61]:
most_common

          name  count
year
1880      John   9655
1881      John   8769
1882      John   9557
1883      John   8894
1884      John   9388
1885      Mary   9128
1886      Mary   9889
1887      Mary   9888
1888      Mary  11754
1889      Mary  11648
1890      Mary  12078
1891      Mary  11703
1892      Mary  13172
1893      Mary  12784
1894      Mary  13151
1895      Mary  13446
1896      Mary  13811
1897      Mary  13413
1898      Mary  14406
1899      Mary  13172
1900      Mary  16707
1901      Mary  13136
1902      Mary  14486
1903      Mary  14275
1904      Mary  14962
1905      Mary  16067
1906      Mary  16370
1907      Mary  17580
1908      Mary  18666
1909      Mary  19259
...        ...    ...
1986   Michael  64188
1987   Michael  63638
1988   Michael  64117
1989   Michael  65378
1990   Michael  65275
1991   Michael  60783
1992   Michael  54384
1993   Michael  49551
1994   Michael  44462
1995   Michael  41404
1996   Michael  38364
1997   Michael  37545
1998   Michael  36615
1999     Jacob  35346
2000     Jacob  34467
2001     Jacob  32531
2002     Jacob  30558
2003     Jacob  29620
2004     Jacob  27873
2005     Jacob  25822
2006     Jacob  24832
2007     Jacob  24259
2008     Jacob  22574
2009  Isabella  22283
2010  Isabella  22890
2011    Sophia  21824
2012    Sophia  22279
2013    Sophia  21171
2014      Emma  20886
2015      Emma  20355

[136 rows x 2 columns]

In [63]:
xy_mc = most_common.copy()
xy_mc.columns = ["name", "y"]
xy_mc.index.name = "x"
xy_mc.to_csv("idyll-project1/data/most_common2.csv")